database:
  host: ""
  username: ""
  password: ""

roles:
  - name: "mod"
    display: "[MOD]"
    permission: 2

permissions:
  - perm: "ADMIN"
    desc: "Admin"
    placeholder: "NETHER_STAR"

  - perm: "KICK_MEMBER"
    desc: "Kick players"
    placeholder: "IRON_SWORD"

  - perm: "BAN_MEMBER"
    desc: "Ban players"
    placeholder: "DIAMOND_SWORD"

  - perm: "UNBAN_MEMBER"
    desc: "Unban players"
    placeholder: "SHIELD"

  - perm: "MUTE_MEMBER"
    desc: "Mute players"
    placeholder: "BARRIER"

  - perm: "INVSEE"
    desc: "Invsee players"
    placeholder: "ENDER_EYE"

  - perm: "APPEAR_OFFLINE"
    desc: "Appear as offline"
    placeholder: "BARRIER"

  - perm: "TELEPORT"
    desc: "Teleport"
    placeholder: "ENDER_PEARL"

  - perm: "MSG_SPY"
    desc: "Message spy"
    placeholder: "BARRIER"